package GUI;

import event.EventMenuSelected;
import java.awt.Color;
import javax.swing.JComponent;
import BLL.GetData;
import GUI.Ban_ThanhToan.BanHang;
import GUI.Kho_PN_PX.Fr_phieuNhap1;
import GUI.ThucDon_KhuyenMai.QuanLySP;
import GUI.ThucDon_KhuyenMai.QuanLyKM;
import GUI.Kho_PN_PX.QuanLyKho;
import GUI.Nhanvien_khachhang.QLNhanVien_JPanel;
import GUI.Nhanvien_khachhang.QuanLyKH;
import java.io.File;
import java.sql.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author phatl
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public static Connection conn = null; 
    public static Login loginForm = null;
    GetData x = new GetData();
    boolean khoidong = false;
   
    public Dashboard(String user) {
        initComponents();
        header.setUsername(x.getCurrentUser());
        header.setLastLogin(x.getLastLogin());
        setBackground(new Color(0, 0, 0, 0));
        JComponent t = new BanHang();
        menu1.initMoving(Dashboard.this);
        menu1.addEventMenuSelected(new EventMenuSelected() {
            @Override
            public void selected(int index) {
                System.out.print(index);
                if (index == 0 && khoidong==true) {
                    setForm(t);
                } 
                else if (index == 1) {
                    setForm(new QuanLySP());
                }else if (index == 2) {
                    setForm(new QuanLyKM());
                }else if (index == 3) {
                   setForm(new QuanLyKho());
                }else if (index == 4) {
                   setForm(new Fr_phieuNhap1());
                }else if (index == 5) {
                   setForm(new QuanLyKH());
                }else if (index == 6) {
                   setForm(new QLNhanVien_JPanel());
                }
                else if (index == 8) {
                    Logout();
                }
                else if(index == 9)
                {
                    if(JOptionPane.showConfirmDialog(Dashboard.this, "Bạn muốn thoát chương trình ?") == JOptionPane.YES_OPTION)
                        System.exit(0);
                }
            }
        });
        //  set when system open start with home form
       setForm(t);
       khoidong = true;
    }

    private void Logout(){
        final String javaBin = System.getProperty("java.home") + File.separator + "bin" + File.separator + "java";
        //final File currentJar = new File("dist/QuanLyCafe.jar");
        /* Build command: java -jar application.jar */
        final ArrayList<String> command = new ArrayList<String>();
        command.add(javaBin);
        command.add("-jar");
        //System.out.println("path:" +currentJar.getAbsolutePath());
        command.add(new File("dist\\Quanly_CaPhe.jar").getAbsolutePath());

        final ProcessBuilder builder = new ProcessBuilder(command);
        try {
            builder.start();
        } catch (IOException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }
    
    private void setForm(JComponent com) {
        mainPanel1.removeAll();
        mainPanel1.add(com);
        mainPanel1.repaint();
        mainPanel1.revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu1 = new Ultilities.component.Menu();
        header = new Ultilities.component.Header();
        mainPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        mainPanel1.setOpaque(false);
        mainPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mainPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1098, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Ultilities.component.Header header;
    private javax.swing.JPanel mainPanel1;
    private Ultilities.component.Menu menu1;
    // End of variables declaration//GEN-END:variables
}
