/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Nhanvien_khachhang;

import BLL.ExecuteData;
import BLL.GetData;
import DTO.KhachHang;
import GUI.Kho_PN_PX.Fr_phieuNhap1;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VANANH
 */
public class QuanLyKH extends javax.swing.JPanel {

    /**
     * Creates new form Fr_KhachHang
     */
    KhachHang kh = new KhachHang();
    ExecuteData exdt = new ExecuteData();

    public QuanLyKH() {
        initComponents();
        showDataOnTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_tenKH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_gioiTinh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_diemTL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_khachhang = new Ultilities.swing.Controls.Table();
        dcs_hsd = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        btn_sua = new Ultilities.swing.Controls.ButtonGradient();
        btn_them = new Ultilities.swing.Controls.ButtonGradient();
        btn_xoa = new Ultilities.swing.Controls.ButtonGradient();

        setMinimumSize(new java.awt.Dimension(1100, 660));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Tên khách hàng: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        txt_tenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_tenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 26, 370, 30));

        jLabel4.setText(" ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 122, -1, -1));

        txt_gioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_gioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 66, 370, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Số điện thoại: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        txt_sdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 106, 370, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Điểm tích lũy: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        txt_diemTL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_diemTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 370, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Giới tính: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Hạn sử dụng");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        tbl_khachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_khachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_khachhangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_khachhang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 236, 1050, 270));

        dcs_hsd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(dcs_hsd, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 380, 30));

        btn_sua.setText("Sửa");
        btn_sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_suaMouseClicked(evt);
            }
        });

        btn_them.setText("Thêm");
        btn_them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themMouseClicked(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_xoaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1073, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themMouseClicked
        // TODO add your handling code here:
        try {
            String tenKH = txt_tenKH.getText();
            String gioitinh = txt_gioiTinh.getText();
            String sdt = txt_sdt.getText();
            String tl = txt_diemTL.getText();
            int dtl = Integer.parseInt(tl);
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(dcs_hsd.getDate());
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String t = dateFormat.format(calendar.getTime());
            kh.setTenkh(tenKH);
            kh.setGioitinh(gioitinh);
            kh.setSdt(sdt);
            kh.setDiemtichluy(String.format("%s", dtl));
            kh.setHsd(t);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn thông tin đầy đủ hoặc " + ex.getMessage());
            return;
        }
        if (ExecuteData.insertKH(kh)) {
            JOptionPane.showMessageDialog(this, "Thêm Thành Công");
            resetText();
            showDataOnTable();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }

    }//GEN-LAST:event_btn_themMouseClicked

    private void btn_xoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xoaMouseClicked
        // TODO add your handling code here:
        int row = tbl_khachhang.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng muốn xóa");
            return;
        }
        kh.setMakh(tbl_khachhang.getValueAt(row, 0).toString());
        if (ExecuteData.deleteKH(kh)) {
            JOptionPane.showMessageDialog(this, "Xóa Thành Công");
            resetText();
            showDataOnTable();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }

    }//GEN-LAST:event_btn_xoaMouseClicked

    private void btn_suaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_suaMouseClicked
        // TODO add your handling code here:
        try {
            String tenKH = txt_tenKH.getText();
            String gioitinh = txt_gioiTinh.getText();
            String sdt = txt_sdt.getText();
            String tl = txt_diemTL.getText();
            int dtl = Integer.parseInt(tl);
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(dcs_hsd.getDate());
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String t = dateFormat.format(calendar.getTime());
            int row = tbl_khachhang.getSelectedRow();
            kh.setMakh(tbl_khachhang.getValueAt(row, 0).toString());
            kh.setTenkh(tenKH);
            kh.setGioitinh(gioitinh);
            kh.setSdt(sdt);
            kh.setDiemtichluy(String.format("%s", dtl));
            kh.setHsd(t);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn thông tin đầy đủ hoặc " + ex.getMessage());
            return;
        }
        if(ExecuteData.updateKH(kh))
        {
            JOptionPane.showMessageDialog(this, "Sửa Thành Công");
           resetText();
           showDataOnTable();
        }else
        {
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
       
    }//GEN-LAST:event_btn_suaMouseClicked

    private void tbl_khachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_khachhangMouseClicked
        // TODO add your handling code here:
        int row = tbl_khachhang.getSelectedRow();
        if (row != -1) {
            txt_tenKH.setText(tbl_khachhang.getValueAt(row, 1).toString());
            txt_gioiTinh.setText(tbl_khachhang.getValueAt(row, 2).toString());
            txt_sdt.setText(tbl_khachhang.getValueAt(row, 3).toString());
            txt_diemTL.setText(tbl_khachhang.getValueAt(row, 4).toString());
            Date date = new Date();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String dateStr = tbl_khachhang.getValueAt(row, 5).toString();
            try {
                dcs_hsd.setDate(dateFormat.parse(dateStr));
            } catch (ParseException ex) {
                Logger.getLogger(Fr_phieuNhap1.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn dòng nào!!!");
        }
    }//GEN-LAST:event_tbl_khachhangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Ultilities.swing.Controls.ButtonGradient btn_sua;
    private Ultilities.swing.Controls.ButtonGradient btn_them;
    private Ultilities.swing.Controls.ButtonGradient btn_xoa;
    private com.toedter.calendar.JDateChooser dcs_hsd;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private Ultilities.swing.Controls.Table tbl_khachhang;
    private javax.swing.JTextField txt_diemTL;
    private javax.swing.JTextField txt_gioiTinh;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_tenKH;
    // End of variables declaration//GEN-END:variables
    GetData x;

    public void showDataOnTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_khachhang.getModel();
        x = new GetData();
        ArrayList arr = x.getDataKH();
        String[] tenCot = {"Mã khách hàng", "Tên khách hàng", "Giới tính", "Số điện thoại", "Điểm tích lũy", "Hạn Sử Dụng"};
        model.setDataVector((Object[][]) arr.get(1), tenCot);
        tbl_khachhang.setRowHeight(50);
        
    }

    private void resetText() {
        txt_tenKH.setText("");
        txt_gioiTinh.setText("");
        txt_sdt.setText("");
        txt_diemTL.setText("");
        Date date = new Date();
        System.out.println(date);
    }
}
