/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Kho_PN_PX;

import BLL.ExecuteData;
import BLL.GetData;
import DTO.ChiTietPhieuNhap;
import DTO.NhanVien;
import DTO.ThucDon;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VANANH
 */
public class Fr_phieuNhap2 extends javax.swing.JPanel {

    /**
     * Creates new form Fr_phieuNhap2
     */
    public Fr_phieuNhap2() {
        initComponents();
    }
    String mapn=null;
    public Fr_phieuNhap2(String mapn) {
        initComponents();
        this.mapn = mapn;
        lbl_pn.setText(mapn);
        loadCTPhieuNhap(mapn);
    }
    GetData getdata = new GetData();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_pn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_ncc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_dongia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_soluong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbo_sp = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new Ultilities.swing.Controls.Table();
        jPanel3 = new javax.swing.JPanel();
        btn_Them = new Ultilities.swing.Controls.ButtonGradient();
        btn_Xoa = new Ultilities.swing.Controls.ButtonGradient();
        btn_sua = new Ultilities.swing.Controls.ButtonGradient();

        setMinimumSize(new java.awt.Dimension(1100, 660));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Chi tiết phiếu nhập");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Mã phiếu nhập");

        lbl_pn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_pn.setText(",");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(jLabel3)
                .addGap(53, 53, 53)
                .addComponent(lbl_pn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lbl_pn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Tên nhà cung cấp:");

        txt_ncc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Đơn giá:");

        txt_dongia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText(" Số lượng:");

        txt_soluong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Sản phẩm");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_dongia, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(txt_soluong))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txt_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbo_sp, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_dongia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbo_sp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        btn_Them.setText("Thêm");
        btn_Them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThemMouseClicked(evt);
            }
        });

        btn_Xoa.setText("Xóa");
        btn_Xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XoaMouseClicked(evt);
            }
        });

        btn_sua.setText("Sửa");
        btn_sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_suaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1088, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)
                    .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThemMouseClicked
        // TODO add your handling code here:
        ChiTietPhieuNhap pn = new ChiTietPhieuNhap();
        if(txt_soluong.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập số lượng");
            return;
        }
        else
        {
            if(txt_dongia.getText().isEmpty() || txt_ncc.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Bạn chưa điền đầy đủ thông tin");
                return;
            }
            int sl = Integer.parseInt(txt_soluong.getText());
            if(sl>=0)
            {
                pn.setSoluong(sl);
                float gia = Float.parseFloat(txt_dongia.getText());
                if(gia<0)
                {
                    JOptionPane.showMessageDialog(this, "Giá không được bé hơn 0");
                    return; 
                }
                pn.setGianhap(gia);
                pn.setTenncc(txt_ncc.getText());
                ThucDon td = (ThucDon) cbo_sp.getSelectedItem();
                
                pn.setNguyenlieumanl(td.getId());
                pn.setPhieunhapmapn(mapn);
                if(ExecuteData.insertCTPN(pn))
                {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    return; 
                }else
                {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
                    return; 
                }
            }
            else
            {
                
                    JOptionPane.showMessageDialog(this, "Số lượng không được bé hơn 0");
                    return; 
            }
        }
        
        
        
        
    }//GEN-LAST:event_btn_ThemMouseClicked

    private void btn_XoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XoaMouseClicked
        // TODO add your handling code here:
        ChiTietPhieuNhap pn = new ChiTietPhieuNhap();
        pn.setPhieunhapmapn(mapn);
        if(ExecuteData.deleteCTPN(pn))
        {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            return; 
        }else
        {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
            return; 
        }
        

    }//GEN-LAST:event_btn_XoaMouseClicked

    private void btn_suaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_suaMouseClicked
        // TODO add your handling code here:
        ChiTietPhieuNhap pn = new ChiTietPhieuNhap();
        if(txt_soluong.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập số lượng");
            return;
        }
        else
        {
            if(txt_dongia.getText().isEmpty() || txt_ncc.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Bạn chưa điền đầy đủ thông tin");
                return;
            }
            int sl = Integer.parseInt(txt_soluong.getText());
            if(sl>=0)
            {
                pn.setSoluong(sl);
                float gia = Float.parseFloat(txt_dongia.getText());
                if(gia<0)
                {
                    JOptionPane.showMessageDialog(this, "Giá không được bé hơn 0");
                    return; 
                }
                pn.setGianhap(gia);
                pn.setTenncc(txt_ncc.getText());
                pn.setPhieunhapmapn(mapn);
                ThucDon td = (ThucDon) cbo_sp.getSelectedItem();
                pn.setNguyenlieumanl(td.getId());
                if(ExecuteData.updateCTPN(pn))
                {
                    JOptionPane.showMessageDialog(this, "Sửa thành công");
                    return; 
                }else
                {
                    JOptionPane.showMessageDialog(this, "Sửa thất bại");
                    return; 
                }
            }
            else
            {
                
                    JOptionPane.showMessageDialog(this, "Số lượng không được bé hơn 0");
                    return; 
            }
        }

    }//GEN-LAST:event_btn_suaMouseClicked

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:
        int row = table1.getSelectedRow();
        txt_ncc.setText(table1.getValueAt(row, 2).toString());
        txt_dongia.setText(table1.getValueAt(row, 1).toString());
        txt_soluong.setText(table1.getValueAt(row, 0).toString());
        ThucDon t = new ThucDon();
        for(int i = 0 ; i < cbo_sp.getItemCount();i++)
        {
            t = (ThucDon) cbo_sp.getItemAt(i);
            if(t.getId().equals(table1.getValueAt(row, 4).toString()))
            {
                cbo_sp.setSelectedIndex(i);
                break;
            }
        }
    }//GEN-LAST:event_table1MouseClicked

    void loadCTPhieuNhap(String ma) {
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        String[] tenCot = {"Mã Phiếu nhập", "Ngày nhập", "Nhân viên"};
        model.setDataVector(getdata.getDataCTPhieuNhap(ma), tenCot);
    }

    DefaultComboBoxModel<ThucDon> model_cbo_td ;
    void loadcomboNV()
    {
        // Khởi tạo một danh sách các chuỗi
        Object[][] info1 = (Object[][])getdata.getDataDSSP().get(1);
        model_cbo_td = new DefaultComboBoxModel<>();
        for (Object[] innerList : info1) {
            ThucDon td = new ThucDon();
            if (innerList[0] instanceof String) {
                td.setId((String) innerList[0]);

            }
            if (innerList[1] instanceof String) {
                td.setName((String) innerList[1]);
            }
            model_cbo_td.addElement(td);
        }
        cbo_sp.setModel(model_cbo_td);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Ultilities.swing.Controls.ButtonGradient btn_Them;
    private Ultilities.swing.Controls.ButtonGradient btn_Xoa;
    private Ultilities.swing.Controls.ButtonGradient btn_sua;
    private javax.swing.JComboBox<ThucDon> cbo_sp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_pn;
    private Ultilities.swing.Controls.Table table1;
    private javax.swing.JTextField txt_dongia;
    private javax.swing.JTextField txt_ncc;
    private javax.swing.JTextField txt_soluong;
    // End of variables declaration//GEN-END:variables
}
