/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ThucDon_KhuyenMai;

import BLL.ExecuteData;
import BLL.GetData;
import DTO.KhuyenMai;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thi Duong
 */
public class QuanLyKM extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyKM
     */
    KhuyenMai km = new KhuyenMai();
    ExecuteData exdt = new ExecuteData();
    public QuanLyKM() {
        initComponents();
        showDataOnTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btn_them = new Ultilities.swing.Controls.ButtonGradient();
        btn_xoa = new Ultilities.swing.Controls.ButtonGradient();
        btn_sua = new Ultilities.swing.Controls.ButtonGradient();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Bg_3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_khuyenmai = new Ultilities.swing.Controls.Table();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_tenkm = new Ultilities.swing.Controls.TextField();
        txt_tile = new Ultilities.swing.Controls.TextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 660));
        setPreferredSize(new java.awt.Dimension(1100, 660));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 476, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 222, -1, -1));

        btn_them.setText("Thêm");
        btn_them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themMouseClicked(evt);
            }
        });
        jPanel2.add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 50));

        btn_xoa.setText("Xóa");
        btn_xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_xoaMouseClicked(evt);
            }
        });
        jPanel2.add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 100, 50));

        btn_sua.setText("Sửa");
        btn_sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_suaMouseClicked(evt);
            }
        });
        jPanel2.add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 100, 50));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 460, 80));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ KHUYẾN MÃI");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        Bg_3.setBackground(new java.awt.Color(255, 161, 108));
        Bg_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bg_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ultilities/icon/bg3.jpg"))); // NOI18N
        Bg_3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(Bg_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 800, 400));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 41, 740, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ultilities/icon/gift-voucher.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 15, 153, -1));

        tbl_khuyenmai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_khuyenmai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_khuyenmaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_khuyenmai);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 521, 452));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tên khuyến mãi :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Tỉ lệ :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 52, -1));

        txt_tenkm.setForeground(new java.awt.Color(0, 0, 0));
        txt_tenkm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_tenkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenkmActionPerformed(evt);
            }
        });
        jPanel1.add(txt_tenkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 263, -1));

        txt_tile.setForeground(new java.awt.Color(0, 0, 0));
        txt_tile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txt_tile, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 263, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 180, 480, 170));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themMouseClicked
        // TODO add your handling code here:
        String tenKM = txt_tenkm.getText();
        String tile = txt_tile.getText();
        Float kq = Float.parseFloat(tile)/100;
        km.setTenkm(tenKM);
        km.setTile(kq);
        exdt.insertKM(km);
            JOptionPane.showMessageDialog(this, "Thêm Thành Công");
        resetText();
        showDataOnTable();
    }//GEN-LAST:event_btn_themMouseClicked

    private void tbl_khuyenmaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_khuyenmaiMouseClicked
        // TODO add your handling code here:
        int row = tbl_khuyenmai.getSelectedRow();
        if (row != -1) {
            txt_tenkm.setText(tbl_khuyenmai.getValueAt(row, 1).toString());
            txt_tile.setText(tbl_khuyenmai.getValueAt(row, 2).toString()); 
        } else {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn dòng nào!!!");
        }
    }//GEN-LAST:event_tbl_khuyenmaiMouseClicked

    private void btn_xoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xoaMouseClicked
        // TODO add your handling code here:
        int row = tbl_khuyenmai.getSelectedRow();
        km.setMakm(tbl_khuyenmai.getValueAt(row, 0).toString());
        exdt.deleteKM(km); 
            JOptionPane.showMessageDialog(this, "Xóa Thành Công");
        resetText();
        showDataOnTable();
    }//GEN-LAST:event_btn_xoaMouseClicked

    private void btn_suaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_suaMouseClicked
        // TODO add your handling code here:
        String tenKM = txt_tenkm.getText();
        String tiLe = txt_tile.getText();
        int row = tbl_khuyenmai.getSelectedRow();
        km.setMakm(tbl_khuyenmai.getValueAt(row, 0).toString());
        km.setTenkm(tenKM);
        km.setTile(Float.parseFloat(tiLe));
        exdt.updateKM(km);
            JOptionPane.showMessageDialog(this, "Sửa Thành Công");
        resetText();
        showDataOnTable(); 
    }//GEN-LAST:event_btn_suaMouseClicked

    private void txt_tenkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenkmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenkmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg_3;
    private Ultilities.swing.Controls.ButtonGradient btn_sua;
    private Ultilities.swing.Controls.ButtonGradient btn_them;
    private Ultilities.swing.Controls.ButtonGradient btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private Ultilities.swing.Controls.Table tbl_khuyenmai;
    private Ultilities.swing.Controls.TextField txt_tenkm;
    private Ultilities.swing.Controls.TextField txt_tile;
    // End of variables declaration//GEN-END:variables
    GetData x ;
    public void showDataOnTable(){
        DefaultTableModel model = (DefaultTableModel)tbl_khuyenmai.getModel();
        x = new GetData();
        ArrayList arr =  x.getDataKM();
        String[] tenCot = {"Mã Khuyễn mãi","Tên khuyến mãi","Tỉ lệ"};
        model.setDataVector((Object[][])arr.get(1), tenCot);
        tbl_khuyenmai.setRowHeight(50);
    }
    private void resetText() {
        txt_tenkm.setText("");
        txt_tile.setText("");
    }
}
