/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Ban_ThanhToan;

import BLL.GetData;
import DTO.ChiTietHoaDon;
import DTO.HoaDon;
import DTO.PhanLoai;
import GUI.UserUI.EditUser;
import Ultilities.ConvertData.ConvertDataORCL;
import Ultilities.swing.Controls.ButtonColumn;
import static com.sun.java.accessibility.util.AWTEventMonitor.addWindowListener;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.math.BigDecimal;
import java.nio.ByteBuffer;
import java.sql.Blob;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import oracle.sql.RAW;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author HieuThao
 */
public class BanHang
        extends javax.swing.JPanel {

    /**
     * Creates new form ThanhToan
     */
    private JPanel previousForm;

    public BanHang() {
        initComponents();
        loadPhanLoai();
        loadHoadon();
        btn_khachhang.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                previousForm = BanHang.this; // Lưu lại đối tượng của form hiện tại vào biến previousForm
                KhachHang kh = new KhachHang();
                kh.setVisible(true);
                kh.addWindowListener(new WindowAdapter() {
                    public void windowClosed(WindowEvent e) {
                        if (kh.sdt == null) {
                            lbl_sdt.setText("Unknown");
                        } else {
                            Object[][] obj = getdata.getdataTenKH(kh.sdt);
                            lbl_sdt.setText(obj[0][0].toString());
                            lbl_dtl.setText(obj[0][1].toString());
                        }
                    }
                });

            }
        });
        phanloai.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    GetData getdata = new GetData();

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comboBoxSuggestion5 = new Ultilities.swing.Controls.ComboBoxSuggestion();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        btn_Thanhtoan1 = new Ultilities.swing.Controls.ButtonGradient();
        buttonGradient1 = new Ultilities.swing.Controls.ButtonGradient();
        buttonGradient3 = new Ultilities.swing.Controls.ButtonGradient();
        buttonGradient4 = new Ultilities.swing.Controls.ButtonGradient();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new Ultilities.swing.Controls.Table();
        textField1 = new Ultilities.swing.Controls.TextField();
        jPanel2 = new javax.swing.JPanel();
        cbo_hoadon = new Ultilities.swing.Controls.ComboBoxSuggestion();
        btn_taohd = new Ultilities.swing.Controls.ButtonGradient();
        btn_taohd1 = new Ultilities.swing.Controls.ButtonGradient();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_khachhang = new Ultilities.swing.Controls.ButtonGradient();
        jLabel2 = new javax.swing.JLabel();
        lbl_sdt = new javax.swing.JLabel();
        lbl_dtl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Hình thức");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Tổng số lượng");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Tổng thanh toán");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText(".");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText(".");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Khuyến mãi");

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton2.setText("Tiền mặt");

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton1.setText("Chuyển Khoản");

        btn_Thanhtoan1.setText("Thanh toán");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(226, 409, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxSuggestion5, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Thanhtoan1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxSuggestion5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btn_Thanhtoan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(28, 28, 28))))
        );

        buttonGradient1.setForeground(new java.awt.Color(0, 0, 0));
        buttonGradient1.setText("Tăng");
        buttonGradient1.setColor1(new java.awt.Color(204, 204, 204));
        buttonGradient1.setColor2(new java.awt.Color(204, 204, 204));

        buttonGradient3.setForeground(new java.awt.Color(0, 0, 0));
        buttonGradient3.setText("Giảm");
        buttonGradient3.setColor1(new java.awt.Color(204, 204, 204));
        buttonGradient3.setColor2(new java.awt.Color(204, 204, 204));

        buttonGradient4.setForeground(new java.awt.Color(0, 0, 0));
        buttonGradient4.setText("Xóa");
        buttonGradient4.setColor1(new java.awt.Color(204, 204, 204));
        buttonGradient4.setColor2(new java.awt.Color(204, 204, 204));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table2);

        textField1.setForeground(new java.awt.Color(0, 0, 0));
        textField1.setText("Tăng/giảm");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonGradient3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonGradient4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 30, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonGradient3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonGradient4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, 590, 610));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        cbo_hoadon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_taohd.setText("Tạo");
        btn_taohd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_taohdMouseClicked(evt);
            }
        });

        btn_taohd1.setText("Hủy");
        btn_taohd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_taohd1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(cbo_hoadon, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(btn_taohd, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_taohd1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(cbo_hoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_taohd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_taohd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ultilities/icon/customer-review.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 60, 60));

        btn_khachhang.setText("Khách hàng");
        btn_khachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_khachhangMouseClicked(evt);
            }
        });
        jPanel1.add(btn_khachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 110, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ultilities/icon/coins.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 50, 50));

        lbl_sdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_sdt.setText(".");
        jPanel1.add(lbl_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 180, -1));

        lbl_dtl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_dtl.setText(".");
        jPanel1.add(lbl_dtl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 60, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 570, 60));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 580, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_taohdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_taohdMouseClicked
        // TODO add your handling code here:
        int sohd = cbo_hoadon.getItemCount() + 1;
        data_cbo.add("Hóa đơn " + sohd);
        model_cbo_hd = new DefaultComboBoxModel<>();
        for (String s : data_cbo) {
            model_cbo_hd.addElement(s);
        }
        cbo_hoadon.setModel(model_cbo_hd);
    }//GEN-LAST:event_btn_taohdMouseClicked

    private void btn_taohd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_taohd1MouseClicked
        // TODO add your handling code here:
        int sohd = cbo_hoadon.getSelectedIndex();
        cbo_hoadon.removeItemAt(sohd);
        data_cbo.remove(sohd);
    }//GEN-LAST:event_btn_taohd1MouseClicked
    KhachHang t = null;
    private void btn_khachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_khachhangMouseClicked
        // TODO add your handling code here:
        

    }//GEN-LAST:event_btn_khachhangMouseClicked

    // <editor-fold defaultstate="collapsed" desc="Phần bên trái">      
    JTabbedPane phanloai ;
    void loadPhanLoai() {
        phanloai = new JTabbedPane();
        ArrayList info = getdata.getDataPhanLoai();
        Object[][] info1 = (Object[][]) info.get(1);
        PhanLoai lm = new PhanLoai();
        for (Object[] innerList : info1) {
            if (innerList[1] instanceof String) {
                lm.setMaLoai((String) innerList[0]);
            }
            if (innerList[0] instanceof String) {
                lm.setTenLoai((String) innerList[1]);
            }
            JPanel foodPanel = new JPanel(new BorderLayout()); // Tạo panel mới cho mỗi tabbedpane
             JTable table = new JTable();
            JScrollPane Scroll = new JScrollPane(table);
            foodPanel.add(Scroll, BorderLayout.CENTER);
            loadDataMon(lm.getMaLoai(), table, Scroll);
            phanloai.addTab(lm.getTenLoai(), foodPanel);
        }
        this.add(phanloai, new AbsoluteConstraints(10, 10, 510, 640));
    }

    void loadDataMon(String tenloai, JTable table, JScrollPane Scroll) {
        Blob imageBlob = null;
        int price = 0;
        String name = null;
        String id = null;
        String kc =null;
        ArrayList info = getdata.getDataThucDon(tenloai);
        System.out.println("Type of info: " + info.getClass());
        System.out.println("Type of info: " + info.get(1).getClass());

        // Set up the table with column names
        String[] columnNames = {"Mã món","Tên món","Kích cỡ", "Giá", "Trạng thái", "Hình ảnh"};
        table.setModel(new DefaultTableModel(new Object[][]{}, columnNames) {
            Class[] columTypes = new Class[]{
                Object.class,Object.class,Object.class, Object.class, Object.class, ImageIcon.class
            };

            public Class getColumnClass(int columnIndex) {
                return columTypes[columnIndex];
            }
        });
        Scroll.setViewportView(table);
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.addColumn("");
        ButtonColumn btnCol = new ButtonColumn(table, clickMon, columnNames.length, "Chọn");
        String trangthai = null;
        // Add the data rows to the table
        Object[][] info1 = (Object[][]) info.get(1);
        for (Object[] innerList : info1) {

            if (innerList[0] instanceof String) {
                id = (String) innerList[0];
            }
            if (innerList[5] instanceof Blob) {
                imageBlob = (Blob) innerList[5];
            }
            if (innerList[3] instanceof BigDecimal) {
                price = ((BigDecimal) innerList[3]).intValue();
            }
            if (innerList[1] instanceof String) {
                name = (String) innerList[1];
            }
            if (innerList[2] instanceof String) {
                kc = (String) innerList[2];
            }
            if (innerList[4] instanceof byte[]) {
                byte[] byteArr = (byte[]) innerList[4];
                trangthai = Byte.toString(byteArr[0]);
                if (trangthai.compareTo("1") == 0) {
                    trangthai = "Còn";
                } else {
                    trangthai = "Đã hết";
                }
            }

            BufferedImage image;
            try {
                try {
                    image = ImageIO.read(imageBlob.getBinaryStream());
                    Image scaledImage = image.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
                    ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
                    // Add the row data to the table model
                    Object[] rowData = {id,name,kc, price, trangthai, scaledImageIcon};
                    model.addRow(rowData);
                } catch (IOException ex) {
                    Logger.getLogger(ChonMon.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ChonMon.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        table.setRowHeight(100);
    }
    ArrayList<HoaDon> hd = new  ArrayList<>();
    Action clickMon = new AbstractAction() {
        public void actionPerformed(ActionEvent e) {
            int index = cbo_hoadon.getSelectedIndex();
            JTable table = null;
            // Lấy JTable tại tab index = 0 trong JTabbedPane có tên là tabbedPane
            int selectindex = phanloai.getSelectedIndex();
            JScrollPane srcoll = null;
            Component selectedComponent = phanloai.getSelectedComponent();
            if (selectedComponent instanceof JPanel) {
                JPanel Panel = (JPanel) selectedComponent;
                Component[] t = Panel.getComponents();
                for(Component comp: t)
                {
                    if(comp instanceof JScrollPane)
                    {
                        srcoll = (JScrollPane) comp;
                        table = (JTable)srcoll.getViewport().getView();
                    }
                        
                }
                // do something with the view component
            } else {
                System.out.println(selectedComponent.getClass());
            }

            //JTable table = (JTable)scroll.getViewport().getView();

            int r = table.getSelectedRow();
            // Lấy giá trị tại hàng rowIndex và cột columnIndex

            if(hd.size() <=0)
            {
                HoaDon t = new HoaDon();
                
                t.setDscthd(new ChiTietHoaDon("1",table.getValueAt(r, 0).toString()));
                hd.add(t);
            }
            else
            {
               boolean tontai = false;
               for(ChiTietHoaDon t : hd.get(index).getDscthd())
               {
                   if(t.getThucDonMaMon().equals(table.getValueAt(r, 0).toString()))
                       t.setSoLuong(t.getSoLuong()+1);
               }
            }
            
        }
    };
    // </editor-fold>  
    // <editor-fold defaultstate="collapsed" desc="Phần bên phải"> 
    DefaultComboBoxModel<String> model_cbo_hd = null;
    ArrayList<String> data_cbo = null;

    void loadHoadon() {
        // Khởi tạo một danh sách các chuỗi
        data_cbo = new ArrayList<>();
        data_cbo.add("Hóa đơn 1");
        data_cbo.add("Hóa đơn 2");
        data_cbo.add("Hóa đơn 3");

        // Khởi tạo ComboBoxModel
        model_cbo_hd = new DefaultComboBoxModel<>();

        for (String s : data_cbo) {
            model_cbo_hd.addElement(s);
        }
        cbo_hoadon.setModel(model_cbo_hd);

    }
    DefaultComboBoxModel<String> model_cbo_km = null;

    void loadKhuyenMai() {
        // Khởi tạo một danh sách các chuỗi
        Object[][] km = getdata.getdataKhuyenMai();
        // Khởi tạo ComboBoxModel
        model_cbo_km = new DefaultComboBoxModel<>();
        String t = null;
        for (Object[] s : km) {
            for (Object obj : km) {
                if (obj instanceof String) {
                    t = (String) obj;
                    model_cbo_km.addElement(t);
                }
            }

        }
        cbo_hoadon.setModel(model_cbo_km);

    }

    // </editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Ultilities.swing.Controls.ButtonGradient btn_Thanhtoan1;
    private Ultilities.swing.Controls.ButtonGradient btn_khachhang;
    private Ultilities.swing.Controls.ButtonGradient btn_taohd;
    private Ultilities.swing.Controls.ButtonGradient btn_taohd1;
    private Ultilities.swing.Controls.ButtonGradient buttonGradient1;
    private Ultilities.swing.Controls.ButtonGradient buttonGradient3;
    private Ultilities.swing.Controls.ButtonGradient buttonGradient4;
    private Ultilities.swing.Controls.ComboBoxSuggestion cbo_hoadon;
    private Ultilities.swing.Controls.ComboBoxSuggestion comboBoxSuggestion5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_dtl;
    private javax.swing.JLabel lbl_sdt;
    private Ultilities.swing.Controls.Table table2;
    private Ultilities.swing.Controls.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
