/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Ban_ThanhToan;

import BLL.GetData;
import java.awt.Component;
import java.util.ArrayList;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.ScrollPane;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.Blob;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author HieuThao
 */
public class ChonMon extends javax.swing.JPanel {

    /**
     * Creates new form ChonMon
     */
    public ChonMon() {
        initComponents();
//        loadDataMon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foodPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new Ultilities.swing.Controls.Table();

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table2);

        javax.swing.GroupLayout foodPanelLayout = new javax.swing.GroupLayout(foodPanel);
        foodPanel.setLayout(foodPanelLayout);
        foodPanelLayout.setHorizontalGroup(
            foodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, foodPanelLayout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        foodPanelLayout.setVerticalGroup(
            foodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, foodPanelLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(foodPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(foodPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    GetData getdata = new GetData();

//    void loadDataMon() {
//        Blob imageBlob = null;
//        int price = 0;
//        String name = null;
//        ArrayList info = getdata.getDataThucDon();
//        System.out.println("Type of info: " + info.getClass());
//        System.out.println("Type of info: " + info.get(1).getClass());
//
//        // Set up the table with column names
//        String[] columnNames = {"Tên món", "Giá", "Hình ảnh"};
//        table2.setModel(new DefaultTableModel(new Object[][]{
//        }, columnNames) { Class[] columTypes = new Class[] {
//            Object.class, Object.class, ImageIcon.class
//        };
//        public Class getColumnClass(int columnIndex)
//        {
//            return columTypes[columnIndex];
//        }
//        });
//        jScrollPane1.setViewportView(table2);
//        DefaultTableModel model = (DefaultTableModel) table2.getModel();
//        // Add the data rows to the table
//        Object[][] info1 = (Object[][]) info.get(1);
//        for (Object[] innerList : info1) {
//            for (Object obj : innerList) {
//                if (obj instanceof Blob) {
//                    imageBlob = (Blob) obj;
//                }
//                if (obj instanceof BigDecimal) {
//                    price = ((BigDecimal) obj).intValue();
//                }
//                if (obj instanceof String) {
//                    name = (String) obj;
//                }
//            }
//
//              
//            BufferedImage image;
//            try {
//                try {
//                    image = ImageIO.read(imageBlob.getBinaryStream());
//                    Image scaledImage = image.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
//                    ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
//                      // Add the row data to the table model
//                    Object[] rowData = {name, price, scaledImageIcon};
//                    model.addRow(rowData);
//                } catch (IOException ex) {
//                    Logger.getLogger(ChonMon.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            } catch (SQLException ex) {
//                Logger.getLogger(ChonMon.class.getName()).log(Level.SEVERE, null, ex);
//            }
//                   
//        }
//        table2.setRowHeight(100);
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel foodPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private Ultilities.swing.Controls.Table table2;
    // End of variables declaration//GEN-END:variables

    
}
